// rustc nightly
// -C opt-level=3 -C target-feature=+sse4.2,+pclmulqdq

// Generated by https://github.com/corsix/fast-crc32 using:
//
// ```console
// make generate
// ./generate -i sse -p crc32c -a v1s3x2
// ```
//
// MIT or zlib licensed
#![no_main]

#[cfg(target_arch = "x86")]
use std::arch::x86::*;
#[cfg(target_arch = "x86_64")]
use std::arch::x86_64::*;

#[inline]
#[target_feature(enable = "pclmulqdq")]
fn clmul_lo(a: __m128i, b: __m128i) -> __m128i {
    _mm_clmulepi64_si128::<0>(a, b)
}

#[inline]
#[target_feature(enable = "pclmulqdq")]
fn clmul_hi(a: __m128i, b: __m128i) -> __m128i {
    _mm_clmulepi64_si128::<17>(a, b)
}

#[inline]
#[target_feature(enable = "sse4.2,pclmulqdq")]
fn clmul_scalar(a: u32, b: u32) -> __m128i {
    _mm_clmulepi64_si128::<0>(
        _mm_cvtsi32_si128(a.cast_signed()),
        _mm_cvtsi32_si128(b.cast_signed()),
    )
}

#[inline]
#[target_feature(enable = "sse4.2")]
fn mm_crc32_u64(crc: u32, v: u64) -> u32 {
    #[cfg(target_arch = "x86")]
    {
        let lo = _mm_crc32_u32(crc, v as u32);
        _mm_crc32_u32(lo, (v >> 32) as u32)
    }
    #[cfg(target_arch = "x86_64")]
    {
        _mm_crc32_u64(u64::from(crc), v) as u32
    }
}

#[inline]
#[target_feature(enable = "sse4.2")]
fn mm_extract_epi64<const IMM1: i32>(a: __m128i) -> u64 {
    const { assert!(IMM1 == 0 || IMM1 == 1) };
    #[cfg(target_arch = "x86")]
    {
        let arr: [u64; 2] = unsafe { core::mem::transmute(a) };
        arr[IMM1 as usize]
    }
    #[cfg(target_arch = "x86_64")]
    {
        _mm_extract_epi64::<IMM1>(a).cast_unsigned()
    }
}

// x^n mod P, in log(n) time
#[inline]
#[target_feature(enable = "sse4.2,pclmulqdq")]
fn xnmodp(mut n: u64) -> u32 {
    let mut stack = !1_u64;
    while n > 191 {
        stack = (stack << 1) + (n & 1);
        n = (n >> 1) - 16;
    }
    stack = !stack;
    let mut acc = 0x8000_0000_u32 >> (n & 31);
    n >>= 5;
    while n != 0 {
        acc = _mm_crc32_u32(acc, 0);
        n -= 1;
    }
    loop {
        let low = stack & 1;
        stack >>= 1;
        if stack == 0 {
            break;
        }
        let x = _mm_cvtsi32_si128(acc.cast_signed());
        let y = mm_extract_epi64::<0>(_mm_clmulepi64_si128::<0>(x, x));
        acc = mm_crc32_u64(0, y << low);
    }
    acc
}

#[inline]
#[target_feature(enable = "sse4.2,pclmulqdq")]
fn crc_shift(crc: u32, nbytes: usize) -> __m128i {
    clmul_scalar(crc, xnmodp((nbytes * 8 - 33) as u64))
}

#[unsafe(no_mangle)]
#[target_feature(enable = "sse4.2,pclmulqdq")]
pub unsafe fn crc32c(mut crc0: u32, mut buf: *const u8, mut len: usize) -> u32 {
    crc0 = !crc0;
    while len != 0 && (buf as usize & 7) != 0 {
        crc0 = _mm_crc32_u8(crc0, unsafe { *buf });
        buf = unsafe { buf.add(1) };
        len -= 1;
    }
    if (buf as usize & 8) != 0 && len >= 8 {
        crc0 = mm_crc32_u64(crc0, unsafe { buf.cast::<u64>().read_unaligned() });
        buf = unsafe { buf.add(8) };
        len -= 8;
    }
    if len >= 64 {
        let blk = len / 64;
        let klen = blk * 16;
        let mut buf2 = unsafe { buf.add(klen * 3) };
        let mut crc1 = 0_u32;
        let mut crc2 = 0_u32;
        // First vector chunk.
        let mut x0 = unsafe { _mm_loadu_si128(buf2.cast()) };
        let k = _mm_setr_epi32(
            0xf20c_0dfe_u32.cast_signed(),
            0,
            0x493c_7d27_u32.cast_signed(),
            0,
        );
        buf2 = unsafe { buf2.add(16) };
        len -= 64;
        // Main loop.
        while len >= 64 {
            let y0 = clmul_lo(x0, k);
            x0 = _mm_xor_si128(
                clmul_hi(x0, k),
                _mm_xor_si128(y0, unsafe { _mm_loadu_si128(buf2.cast()) }),
            );
            // Final scalar chunk.
            crc0 = mm_crc32_u64(crc0, unsafe { buf.cast::<u64>().read_unaligned() });
            crc1 = mm_crc32_u64(crc1, unsafe {
                buf.add(klen).cast::<u64>().read_unaligned()
            });
            crc2 = mm_crc32_u64(crc2, unsafe {
                buf.add(klen * 2).cast::<u64>().read_unaligned()
            });
            crc0 = mm_crc32_u64(crc0, unsafe { buf.add(8).cast::<u64>().read_unaligned() });
            crc1 = mm_crc32_u64(crc1, unsafe {
                buf.add(klen + 8).cast::<u64>().read_unaligned()
            });
            crc2 = mm_crc32_u64(crc2, unsafe {
                buf.add(klen * 2 + 8).cast::<u64>().read_unaligned()
            });
            buf = unsafe { buf.add(16) };
            buf2 = unsafe { buf2.add(16) };
            len -= 64;
        }
        crc0 = mm_crc32_u64(crc0, unsafe { buf.cast::<u64>().read_unaligned() });
        crc1 = mm_crc32_u64(crc1, unsafe {
            buf.add(klen).cast::<u64>().read_unaligned()
        });
        crc2 = mm_crc32_u64(crc2, unsafe {
            buf.add(klen * 2).cast::<u64>().read_unaligned()
        });
        crc0 = mm_crc32_u64(crc0, unsafe { buf.add(8).cast::<u64>().read_unaligned() });
        crc1 = mm_crc32_u64(crc1, unsafe {
            buf.add(klen + 8).cast::<u64>().read_unaligned()
        });
        crc2 = mm_crc32_u64(crc2, unsafe {
            buf.add(klen * 2 + 8).cast::<u64>().read_unaligned()
        });
        let vc0 = crc_shift(crc0, klen * 2 + blk * 16);
        let vc1 = crc_shift(crc1, klen + blk * 16);
        let vc2 = crc_shift(crc2, blk * 16);
        let vc = mm_extract_epi64::<0>(_mm_xor_si128(vc0, _mm_xor_si128(vc1, vc2)));
        // Reduce 128 bits to 32 bits, and multiply by x^32.
        crc0 = mm_crc32_u64(0, mm_extract_epi64::<0>(x0));
        crc0 = mm_crc32_u64(crc0, vc ^ mm_extract_epi64::<1>(x0));
        buf = buf2;
    }
    while len >= 8 {
        crc0 = mm_crc32_u64(crc0, unsafe { buf.cast::<u64>().read_unaligned() });
        buf = unsafe { buf.add(8) };
        len -= 8;
    }
    while len != 0 {
        crc0 = _mm_crc32_u8(crc0, unsafe { *buf });
        buf = unsafe { buf.add(1) };
        len -= 1;
    }
    !crc0
}
