[build-system]
requires = ["maturin == 1.15.0"]
build-backend = "maturin"

[tool.maturin]
python-source = "py-src"
module-name = "crc32c_rs._crc32c_rs"

[project]
name = "crc32c-rs"
dynamic = ["version"]
requires-python = ">= 3.11"
description = "High-performance CRC32C implementation compliant with RFC 3720 (iSCSI)"
readme = { file = "README.md", content-type = "text/markdown" }
license = "Unlicense"
license-files = [
    "UNLICENSE",
    "licenses/fast-crc32-LICENSE.MIT.md",
    "licenses/fast-crc32-LICENSE.zlib.md",
    "licenses/crc-fast-rust-LICENSE-MIT",
    "licenses/crc-fast-rust-LICENSE-Zlib",
    "licenses/crc-fast-rust-LICENSE-Apache",
]
authors = [
    { name = "chirizxc", email = "chirizxc@proton.me" }
]
keywords = []
classifiers = [
    "Typing :: Typed",
    "Programming Language :: Rust",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Software Development :: Libraries",
    "Development Status :: 5 - Production/Stable",
]
dependencies = []

[project.urls]
Homepage = "https://github.com/lava-sh/crc32c-rs"
Repository = "https://github.com/lava-sh/crc32c-rs"
Issues = "https://github.com/lava-sh/crc32c-rs/issues"

[dependency-groups]
typos = ["typos == 1.50.1"]
zizmor = ["zizmor == 1.30.0"]
rumdl = ["rumdl == 0.2.66"]
maturin = [
    "maturin == 1.15.0 ; sys_platform != 'linux'",
    "maturin[patchelf] == 1.15.0 ; sys_platform == 'linux'",
]
pytest = ["pytest == 9.1.1"]
tests = [
    { include-group = "pytest" },
    # `collections.abc.Buffer` added in version 3.12.
    "typing-extensions == 4.16.0 ; python_version < '3.12'",
    "archspec == 0.2.6",
    "pytest-check == 2.9.1",
]
wasm-tests = [
    "pytest-pyodide == 0.59.2",
    "pytest-httpserver == 1.1.5",
    { include-group = "pytest" },
]
ci = [
    "ty == 0.0.78",
    "ruff == 0.16.6",
    { include-group = "tests" },
    { include-group = "pytest" },
    { include-group = "maturin" },
]
dev = [
    "rust-just == 1.58.0",
    { include-group = "ci" },
    { include-group = "typos" },
    { include-group = "rumdl" },
    { include-group = "zizmor" },
]
bench = [
    "crc == 8.0.0",
    "crc32c == 2.9.0",
    "fastcrc == 0.3.6",
    "google-crc32c == 1.8.0",
]

[tool.uv.dependency-groups]
wasm-tests = { requires-python = ">= 3.13" }
