target-version = "py311"

line-length = 90

output-prefer-rule-codes = true

include = [
    "py-src/**/*.{py,pyi}",
    "tests/*.py",
    "pyproject.toml",
    "README.md",
    "scripts/table.py"
]

[lint.isort]
force-wrap-aliases = true
combine-as-imports = true
no-lines-before = ["local-folder"]

[lint]
preview = true

select = ["ALL"]
ignore = [
    "ARG",     # Unused method argument
    "D",       # Docstring's
    ########
    "CPY001",  # Check copyright notices within Python files
    "S311",    # Force `random` -> `secrets`
    "ANN401",  # Check `typing.Any`
    "SIM105",  # Force `try-except-pass` -> `contextlib.suppress`
    "RUF105",  # Force `noqa: ...` -> `ruff: ignore[...]`
    #######
    "PLR6201", # Checks for membership tests on list and tuple literals.
    "PTH207",  # Force `glob` -> `Path.glob` or `Path.rglob`
    ########
    "TC001",   # \
    "TC002",   #  ==> `typing.TYPE_CHECKING` block's
    "TC003",   # /
    "TC006",   # Add quotes to type expression in `typing.cast()`
]

[lint.per-file-ignores]
"scripts/table.py" = [
    "INP001", # Check for packages that are missing an `__init__.py` file
    "T201",   # Check for `print` statements
]
"py-src/**/*.pyi" = [
    "PYI021", # Check for the presence of docstrings in stub files
]
"tests/*.py" = [
    "DOC",     # Docstring's
    ######
    "S101",    # Check for uses of the `assert` keyword
    "PLR2004", # Check for the use of unnamed numerical constants ("magic") values in comparisons
]

[lint.flake8-tidy-imports.banned-api]
"contextlib.suppress"    = { msg = "Use `try-except-pass` instead" }
"__future__.annotations" = { msg = "Directly quote annotations instead" }
