[global]
respect-gitignore = true
exclude = [
    ".git/",
    ".github/",
    "benchmarks/python/README.md",
]
include = [
    "README.md",
    "licenses/README.md",
]
disable = [
    "MD041",
]

[MD013]
line_length = 100

[MD033]
allowed-elements = [
    "no-markdown-equivalent",
    "img", "p", "a"
]
