from pathlib import Path

FILE = Path(__file__).resolve().parent
ROOT = FILE.parent
TABLE_RS = ROOT / "src" / "arch" / "table.rs"

POLY = 0x82F63B78
MASK = 0xFFFFFFFF

# Must match `LONG` / `SHORT` in `src/arch/sse42.rs`.
LONG = 8192
SHORT = 256


def generate_table(planes: int) -> list[list[int]]:
    table = []
    for i in range(planes):
        row = []
        for j in range(256):
            crc: int = j
            for _ in range((i + 1) * 8):
                crc = (crc >> 1) ^ ((crc & 1) * POLY)
            row.append(crc)
        table.append(row)
    return table


def gf2_matrix_times(mat: list[int], vec: int) -> int:
    total = 0
    for entry in mat:
        if vec & 1:
            total ^= entry
        vec >>= 1
    return total & MASK


def gf2_matrix_square(mat: list[int]) -> list[int]:
    return [gf2_matrix_times(mat, entry) for entry in mat]


def crc32c_zeros(length: int) -> list[list[int]]:
    odd = [POLY, *(1 << n for n in range(31))]
    even = gf2_matrix_square(odd)
    odd = gf2_matrix_square(even)

    while True:
        even = gf2_matrix_square(odd)
        length >>= 1
        if length == 0:
            break

        odd = gf2_matrix_square(even)
        length >>= 1
        if length == 0:
            even = odd
            break

    return [
        [gf2_matrix_times(even, value << shift) for value in range(256)]
        for shift in (0, 8, 16, 24)
    ]


def fmt_static(name: str, table: list[list[int]]) -> list[str]:
    lines = [
        "#[rustfmt::skip]",
        "#[allow(clippy::unreadable_literal)]",
        f"pub static {name}: [[u32; 256]; {len(table)}] = [[",
    ]
    for i, row in enumerate(table):
        if i > 0:
            lines.append("    ],[")
        for j in range(0, 256, 8):
            values = [f"0x{value:08x}" for value in row[j : j + 8]]
            lines.append(f"    {', '.join(values)},")
    lines.append("]];")
    return lines


def main() -> None:
    lines = [
        "// This file is automatically @generated by scripts/table.py.",
        "// It is not intended for manual editing.",
        "",
        *fmt_static("CRC32C_TABLE", generate_table(16)),
        "",
        *fmt_static("LONG_TABLE", crc32c_zeros(LONG)),
        "",
        *fmt_static("SHORT_TABLE", crc32c_zeros(SHORT)),
    ]

    TABLE_RS.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Generated tables: {TABLE_RS}")


main()
