from pathlib import Path

FILE: Path = Path(__file__).resolve().parent
ROOT: Path = FILE.parent
TABLE_RS: Path = ROOT / "src" / "arch" / "table.rs"

POLY: int = 0x82F63B78


def generate_table(planes: int) -> list[list[int]]:
    table = []
    for i in range(planes):
        row = []
        for j in range(256):
            crc: int = j
            for _ in range((i + 1) * 8):
                crc = (crc >> 1) ^ ((crc & 1) * POLY)
            row.append(crc)
        table.append(row)
    return table


def fmt_table(table: list[list[int]]) -> str:
    lines = [
        "// This file is automatically @generated by scripts/table.py.",
        "// It is not intended for manual editing.",
        "",
        "#[rustfmt::skip]",
        "#[allow(clippy::unreadable_literal)]",
        f"pub static CRC32C_TABLE: [[u32; 256]; {len(table)}] = [[",
    ]
    for i, row in enumerate(table):
        if i > 0:
            lines.append("    ],[")
        for j in range(0, 256, 8):
            chunk = row[j:j + 8]
            hex_values = [f"0x{x:08x}" for x in chunk]
            lines.append(f"    {', '.join(hex_values)},")
    lines.append("]];")
    return "\n".join(lines)


TABLE_RS.write_text(fmt_table(generate_table(16)), encoding="utf-8")
print(f"Generated table: {TABLE_RS}")
