// rustc nightly
// -C opt-level=3 -C target-feature=+crc,+aes

// Generated by https://github.com/corsix/fast-crc32 using:
//
// ```console
// make generate
// ./generate -i neon -p crc32c -a v3s4x2e_v2
// ```
//
// MIT or zlib licensed
#![no_main]

use std::arch::{aarch64::*, asm};

#[inline]
#[target_feature(enable = "aes")]
fn clmul_lo_e(a: uint64x2_t, b: uint64x2_t, c: uint64x2_t) -> uint64x2_t {
    let r;
    unsafe {
        asm!(
            "pmull {r:v}.1q, {a:v}.1d, {b:v}.1d",
            "eor {r:v}.16b, {r:v}.16b, {c:v}.16b",
            r = out(vreg) r,
            a = in(vreg) a,
            b = in(vreg) b,
            c = in(vreg) c,
            options(pure, nomem, nostack),
        );
    }
    r
}

#[inline]
#[target_feature(enable = "aes")]
fn clmul_hi_e(a: uint64x2_t, b: uint64x2_t, c: uint64x2_t) -> uint64x2_t {
    let r;
    unsafe {
        asm!(
            "pmull2 {r:v}.1q, {a:v}.2d, {b:v}.2d",
            "eor {r:v}.16b, {r:v}.16b, {c:v}.16b",
            r = out(vreg) r,
            a = in(vreg) a,
            b = in(vreg) b,
            c = in(vreg) c,
            options(pure, nomem, nostack),
        );
    }
    r
}

#[inline]
#[target_feature(enable = "aes")]
fn clmul_scalar(a: u32, b: u32) -> uint64x2_t {
    let a = vmovq_n_u64(u64::from(a));
    let b = vmovq_n_u64(u64::from(b));
    let r;
    unsafe {
        asm!(
            "pmull {r:v}.1q, {a:v}.1d, {b:v}.1d",
            r = out(vreg) r,
            a = in(vreg) a,
            b = in(vreg) b,
            options(pure, nomem, nostack),
        );
    }
    r
}

#[inline]
#[target_feature(enable = "crc,aes")]
fn xnmodp(mut n: u64) -> u32 {
    let mut stack = !1u64;
    while n > 191 {
        stack = (stack << 1) + (n & 1);
        n = (n >> 1) - 16;
    }
    stack = !stack;

    let mut acc = 0x8000_0000_u32 >> (n & 31);
    n >>= 5;
    while n != 0 {
        acc = __crc32cw(acc, 0);
        n -= 1;
    }

    loop {
        let low = stack & 1;
        stack >>= 1;
        if stack == 0 {
            break;
        }

        let x = vreinterpret_p8_u64(vmov_n_u64(u64::from(acc)));
        let y = vgetq_lane_u64(vreinterpretq_u64_p16(vmull_p8(x, x)), 0);
        acc = __crc32cd(0, y << low);
    }
    acc
}

#[inline]
#[target_feature(enable = "crc,aes")]
fn crc_shift(crc: u32, nbytes: usize) -> uint64x2_t {
    clmul_scalar(crc, xnmodp((nbytes * 8 - 33) as u64))
}

#[target_feature(enable = "crc,aes")]
#[unsafe(no_mangle)]
pub unsafe fn crc32c(mut crc0: u32, mut buf: *const u8, mut len: usize) -> u32 {
    crc0 = !crc0;
    while len != 0 && (buf as usize & 7) != 0 {
        crc0 = unsafe { __crc32cb(crc0, *buf) };
        buf = unsafe { buf.add(1) };
        len -= 1;
    }
    if (buf as usize & 8) != 0 && len >= 8 {
        crc0 = unsafe { __crc32cd(crc0, *(buf.cast::<u64>())) };
        buf = unsafe { buf.add(8) };
        len -= 8;
    }

    if len >= 112 {
        let end = unsafe { buf.add(len) };
        let blk = len / 112;
        let klen = blk * 16;
        let mut buf2 = unsafe { buf.add(klen * 4) };
        let limit = unsafe { buf.add(klen).sub(32) };
        let mut crc1 = 0u32;
        let mut crc2 = 0u32;
        let mut crc3 = 0u32;

        // First vector chunk.
        let mut x0 = unsafe { vld1q_u64(buf2.cast::<u64>()) };
        let mut x1 = unsafe { vld1q_u64(buf2.add(16).cast::<u64>()) };
        let mut x2 = unsafe { vld1q_u64(buf2.add(32).cast::<u64>()) };
        let k_values = [0x1c29_1d04_u64, 0xddc0_152b_u64];
        let mut k = unsafe { vld1q_u64(k_values.as_ptr()) };
        buf2 = unsafe { buf2.add(48) };

        // Main loop.
        while buf <= limit {
            let y0 = clmul_lo_e(x0, k, unsafe { vld1q_u64(buf2.cast::<u64>()) });
            x0 = clmul_hi_e(x0, k, y0);
            let y1 = clmul_lo_e(x1, k, unsafe { vld1q_u64(buf2.add(16).cast::<u64>()) });
            x1 = clmul_hi_e(x1, k, y1);
            let y2 = clmul_lo_e(x2, k, unsafe { vld1q_u64(buf2.add(32).cast::<u64>()) });
            x2 = clmul_hi_e(x2, k, y2);

            unsafe {
                crc0 = __crc32cd(crc0, *(buf.cast::<u64>()));
                crc1 = __crc32cd(crc1, *(buf.add(klen).cast::<u64>()));
                crc2 = __crc32cd(crc2, *(buf.add(klen * 2).cast::<u64>()));
                crc3 = __crc32cd(crc3, *(buf.add(klen * 3).cast::<u64>()));
                crc0 = __crc32cd(crc0, *(buf.add(8).cast::<u64>()));
                crc1 = __crc32cd(crc1, *(buf.add(klen + 8).cast::<u64>()));
                crc2 = __crc32cd(crc2, *(buf.add(klen * 2 + 8).cast::<u64>()));
                crc3 = __crc32cd(crc3, *(buf.add(klen * 3 + 8).cast::<u64>()));
            }

            buf = unsafe { buf.add(16) };
            buf2 = unsafe { buf2.add(48) };
        }

        // Reduce x0 ... x2 to just x0.
        let k_values = [0xf20c_0dfe_u64, 0x493c_7d27_u64];
        k = unsafe { vld1q_u64(k_values.as_ptr()) };
        let y0 = clmul_lo_e(x0, k, x1);
        x0 = clmul_hi_e(x0, k, y0);
        x1 = x2;
        let y0 = clmul_lo_e(x0, k, x1);
        x0 = clmul_hi_e(x0, k, y0);

        // Final scalar chunk.
        unsafe {
            crc0 = __crc32cd(crc0, *(buf.cast::<u64>()));
            crc1 = __crc32cd(crc1, *(buf.add(klen).cast::<u64>()));
            crc2 = __crc32cd(crc2, *(buf.add(klen * 2).cast::<u64>()));
            crc3 = __crc32cd(crc3, *(buf.add(klen * 3).cast::<u64>()));
            crc0 = __crc32cd(crc0, *(buf.add(8).cast::<u64>()));
            crc1 = __crc32cd(crc1, *(buf.add(klen + 8).cast::<u64>()));
            crc2 = __crc32cd(crc2, *(buf.add(klen * 2 + 8).cast::<u64>()));
            crc3 = __crc32cd(crc3, *(buf.add(klen * 3 + 8).cast::<u64>()));
        }

        let vc0 = crc_shift(crc0, klen * 3 + blk * 48);
        let vc1 = crc_shift(crc1, klen * 2 + blk * 48);
        let vc2 = crc_shift(crc2, klen + blk * 48);
        let vc3 = crc_shift(crc3, blk * 48);
        let vc = vgetq_lane_u64(veorq_u64(veorq_u64(vc0, vc1), veorq_u64(vc2, vc3)), 0);

        // Reduce 128 bits to 32 bits, and multiply by x^32.
        crc0 = __crc32cd(0, vgetq_lane_u64(x0, 0));
        crc0 = __crc32cd(crc0, vc ^ vgetq_lane_u64(x0, 1));
        buf = buf2;
        len = unsafe { end.offset_from(buf).cast_unsigned() };
    }

    if len >= 32 {
        // First vector chunk.
        let mut x0 = unsafe { vld1q_u64(buf.cast::<u64>()) };
        let mut x1 = unsafe { vld1q_u64(buf.add(16).cast::<u64>()) };
        let k_values = [0x3da6_d0cb_u64, 0xba4f_c28e_u64];
        let k = unsafe { vld1q_u64(k_values.as_ptr()) };
        x0 = veorq_u64(vsetq_lane_u64(u64::from(crc0), vmovq_n_u64(0), 0), x0);
        buf = unsafe { buf.add(32) };
        len -= 32;

        // Main loop.
        while len >= 32 {
            let y0 = clmul_lo_e(x0, k, unsafe { vld1q_u64(buf.cast::<u64>()) });
            x0 = clmul_hi_e(x0, k, y0);
            let y1 = clmul_lo_e(x1, k, unsafe { vld1q_u64(buf.add(16).cast::<u64>()) });
            x1 = clmul_hi_e(x1, k, y1);
            buf = unsafe { buf.add(32) };
            len -= 32;
        }

        // Reduce x0 ... x1 to just x0.
        let k_values = [0xf20c_0dfe_u64, 0x493c_7d27_u64];
        let k = unsafe { vld1q_u64(k_values.as_ptr()) };
        let y0 = clmul_lo_e(x0, k, x1);
        x0 = clmul_hi_e(x0, k, y0);

        // Reduce 128 bits to 32 bits, and multiply by x^32.
        crc0 = __crc32cd(0, vgetq_lane_u64(x0, 0));
        crc0 = __crc32cd(crc0, vgetq_lane_u64(x0, 1));
    }

    while len >= 8 {
        crc0 = unsafe { __crc32cd(crc0, *(buf.cast::<u64>())) };
        buf = unsafe { buf.add(8) };
        len -= 8;
    }
    while len != 0 {
        crc0 = unsafe { __crc32cb(crc0, *buf) };
        buf = unsafe { buf.add(1) };
        len -= 1;
    }
    !crc0
}
